quarkus:
  application:
    name: mission-service
  log:
    level: INFO
    console:
      enable: true
      level: INFO
  datasource:
    db-kind: mariadb
    jdbc:
      driver: org.mariadb.jdbc.Driver
      url: ${RDBMS_URL}
      min-size: 5
      max-size: 20
      initial-size: 5
      validation-query-sql: SELECT 1
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PWD}
  hibernate-orm:
    database:
      generation: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
  kafka:
    health:
      enabled: true
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP}
mp:
  messaging:
    incoming:
      mission-command:
        connector: smallrye-kafka
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        request:
          timeout:
            ms: 30000
        enable:
          auto:
            commit: false
      responder-location-updated:
        connector: smallrye-kafka
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        request:
          timeout:
            ms: 30000
        enable:
          auto:
            commit: false
    outgoing:
      mission-event:
        connector: smallrye-kafka
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        session:
          timeout:
            ms: 6000
        acks: 1

